services:
  - type: web
    name: canvas-web-app
    env: node
    buildCommand: |
      chmod +x render-build.sh
      ./render-build.sh
    startCommand: gunicorn backend.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: NPM_CONFIG_LEGACY_PEER_DEPS
        value: "true"
      - key: NODE_VERSION
        value: 18.x
      - key: NPM_VERSION
        value: 9.x
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free
    buildCommand: |
      npm install -g npm@9.8.1
      npm install
      npm run build
      cd backend
      pip install -r requirements.txt
      cd ..
