services:
  - type: web
    name: canvas-web-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NODE_VERSION
        value: 16.0.0
    plan: free
